## **Лабораторная работа №2**
*Вариант 18*

## Задание 1. 
Создайте массив NumPy размером 3×3, содержащий числа от 1 до 9. Умножьте все элементы массива на 2, а затем замените все элементы больше 10 на 0. Выведите итоговый массив.

In [156]:
import numpy as np
import math

In [158]:
arr = np.matrix('1, 2, 3; 4, 5, 6; 7, 8, 9')

In [160]:
arr2 = arr *2
print(arr2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [162]:
arr2[arr2 > 10] = 0
print(arr2)

[[ 2  4  6]
 [ 8 10  0]
 [ 0  0  0]]


## Задание 2. 
Создайте массив NumPy из 20 случайных целых чисел от 1 до 100. Найдите и выведите все элементы, которые делятся на 5 без остатка. Затем замените их на -1 и выведите обновленный массив

In [165]:
a = np.random.randint(1, 101,20)
print(a)

[43 58 17 95 57 61 33 14 48 81 93 63 68 88 32 12 91 47 82 52]


In [167]:
div_by_5 = a[a %5==0]
print(div_by_5)

[95]


In [169]:
a[a % 5 == 0] = -1
print(a)

[43 58 17 -1 57 61 33 14 48 81 93 63 68 88 32 12 91 47 82 52]


## Задание 3. 
Создайте два массива NumPy размером 1×5, заполненные случайными числами от 0 до 50. Объедините эти массивы в один двумерный массив (по строкам). Разделите полученный массив на два массива, каждый из которых содержит 5 элементов. Выведите все промежуточные и итоговые результаты.

In [172]:
a = np.random.randint(0, 51, 5)
b = np.random.randint(0, 51, 5)
print(f'a = {a}')
print(f'b = {b}')
ab = np.array([a, b])
print(f'ab = {ab}')
a1, b1 = ab
print(f'a1 = {a1}')
print(f'b1 = {b1}')

a = [ 3  6 47 30 13]
b = [29 16  2 39 41]
ab = [[ 3  6 47 30 13]
 [29 16  2 39 41]]
a1 = [ 3  6 47 30 13]
b1 = [29 16  2 39 41]


## Задание 4. 
Создайте массив из 50 чисел, равномерно распределенных от -10 до 10. Вычислите сумму всех элементов, сумму положительных элементов и сумму отрицательных элементов. Выведите результаты

In [222]:
a = np.round(np.linspace(-10,10,50),3)
total_sum = round(np.sum(a),3)
pos_sum = round(np.sum(a[a > 0]),3)
neg_sum = round(np.sum(a[a < 0]),3)
print(a)
print(f"Сумма всех элементов = {total_sum}")
print(f"Сумма положительных элементов = {pos_sum}")
print(f"Сумма отрицательных элементов = {neg_sum}")

[-10.     -9.592  -9.184  -8.776  -8.367  -7.959  -7.551  -7.143  -6.735
  -6.327  -5.918  -5.51   -5.102  -4.694  -4.286  -3.878  -3.469  -3.061
  -2.653  -2.245  -1.837  -1.429  -1.02   -0.612  -0.204   0.204   0.612
   1.02    1.429   1.837   2.245   2.653   3.061   3.469   3.878   4.286
   4.694   5.102   5.51    5.918   6.327   6.735   7.143   7.551   7.959
   8.367   8.776   9.184   9.592  10.   ]
Сумма всех элементов = 0.0
Сумма положительных элементов = 127.552
Сумма отрицательных элементов = -127.552


## Задание 5. 
Создайте: 
- Единичную матрицу размером 4×4. 
- Диагональную матрицу размером 4×4 с диагональными элементами [5,10,15,20] (не использовать циклы).

Найдите сумму всех элементов каждой из этих матриц и сравните результаты

In [252]:
m = np.eye(4)
d = np.matrix('5 0 0 0; 0 10 0 0; 0 0 15 0; 0 0 0 20')
m_sum = np.sum(m)
d_sum = np.sum(d)
print(m)
print(f'Сумма единичной матрицы = {m_sum}')
print(d)
print(f'Сумма единичной матрицы = {d_sum}')
if m_sum > d_sum:
    print("Сумма единичной матрицы больше")
elif d_sum > m_sum:
    print("Сумма диагональной матрицы больше")
else:
    print("Матрицы равны")

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Сумма единичной матрицы = 4.0
[[ 5  0  0  0]
 [ 0 10  0  0]
 [ 0  0 15  0]
 [ 0  0  0 20]]
Сумма единичной матрицы = 50
Сумма диагональной матрицы больше


## Задание 6. 
Создайте две квадратные матрицы NumPy размером 3×3, заполненные случайными целыми числами от 1 до 20. 
Вычислите и выведите: 
- Их сумму 
- Их разность
- Их поэлементное произведение

In [280]:
m1 = np.random.randint(1,21,(3,3))
m2 = np.random.randint(1,21, (3,3))
summ = m1 + m2
diff = m1 - m2
mult = m1 * m2
print(m1)
print(m1)
print(f'Сумма двух матриц = \n {summ}')
print(f'Разность двух матриц = \n {diff}')
print(f'Поэлементное произведение двух матриц = \n {mult}')

[[16 11  6]
 [13 16  8]
 [ 7 14  9]]
[[16 11  6]
 [13 16  8]
 [ 7 14  9]]
Сумма двух матриц = 
 [[21 27 16]
 [27 23 26]
 [12 24 18]]
Разность двух матриц = 
 [[ 11  -5  -4]
 [ -1   9 -10]
 [  2   4   0]]
Поэлементное произведение двух матриц = 
 [[ 80 176  60]
 [182 112 144]
 [ 35 140  81]]


## Задание 7. 
Создайте две матрицы NumPy: 
- Первую размером 2×3, заполненную случайными числами от 1 до 10.
- Вторую размером 3×2, заполненную случайными числами от 1 до 10.

Выполните матричное умножение ( @ или np.dot ) и выведите результат.

In [283]:
ma = np.random.randint(1, 11, (2, 3))
mb = np.random.randint(1, 11, (3, 2))
mult = ma @ mb
print (ma)
print(mb)
print(f'Матричное умножение матриц = \n {mult}')

[[ 9  2  3]
 [10  9  4]]
[[8 5]
 [7 7]
 [4 1]]
Матричное умножение матриц = 
 [[ 98  62]
 [159 117]]


## Задание 8. 
Создайте случайную квадратную матрицу 3×3. Найдите и выведите: 
- определитель этой матрицы; 
- обратную матрицу (если существует, иначе выведите сообщение, что матрица вырождена).

Используйте функции np.linalg.det и np.linalg.inv

In [311]:
mx = np.random.randint(-5,5, (3,3))
det = np.linalg.det(mx)
print(mx)
print(f'Определитель матрицы = {det}')
if det == 0:
    print("Матрица вырожденная, обратной матрицы не существует")
else:
    inv = np.linalg.inv(mx)
    print(f"Обратная матрица = \n {inv}")

[[-1 -1 -5]
 [-3 -4  2]
 [-2  4  3]]
Определитель матрицы = 115.00000000000001
Обратная матрица = 
 [[-0.17391304 -0.14782609 -0.19130435]
 [ 0.04347826 -0.11304348  0.14782609]
 [-0.17391304  0.05217391  0.00869565]]


## Задание 9. 
Создаем матрицу NumPy размером 4×4, содержащую случайные целые числа от 1 до 50. Выводим:
- Исходную матрицу;
- Транспонированную матрицу;
- След матрицы(сумму элементов на главной диагонали)

Используем np.trace для нахождения следа. 

In [316]:
mx = np.random.randint(1,51, (4,4))
tr_mx = np.transpose(mx)
trace = np.trace(mx)
print(f'Исходная матрица: \n {mx}')
print(f'Транспонированная матрица: \n {tr_mx}')
print(f'След матрицы: \n {trace}')

Исходная матрица: 
 [[32  8 15 22]
 [10 11 18 15]
 [32 24 32 12]
 [45  9 45 24]]
Транспонированная матрица: 
 [[32 10 32 45]
 [ 8 11 24  9]
 [15 18 32 45]
 [22 15 12 24]]
След матрицы: 
 99


## Задание 10.
Решить систему линейных уравнений вида:

2x + 3y - z = 5

4х-у+2z=6

-3x+5y+4z=-2

Используйте матричное представление Ax = B , где A – матрица коэффициентов,x – вектор неизвестных, B – вектор правой части. Решите систему с помощью np.linalg.solve и выведите результат.

In [337]:
a = np.matrix('2,3,-1; 4,-1,2; -3,5,4')
b = np.matrix('5;6;-2')
x = np.round(np.linalg.solve(a,b),2)
print(a)
print(b)
print("Решение: ")
print(f"x = {x[0]}, y = {x[1]}, z = {x[2]}")

[[ 2  3 -1]
 [ 4 -1  2]
 [-3  5  4]]
[[ 5]
 [ 6]
 [-2]]
Решение: 
x = [1.64], y = [0.58], z = [0.01]


## Задание 11. Индивидуальное задание
Решить индивидуальное задание согласно варианту 18. Решили полученную систему уравнений с использованием библиотеки NumPy. Для решения системы использовали метод Крамера и матричный метод. Сравнили полученные результаты, с результатами, полученными с помощью np.linalg.solve.

Расчет пропорций в строительстве. Для приготовления бетона используются цемент, песок и гравий. В нормальном соотношении цемент должен составлять 1/4 смеси, песок — 1/3, а остальное — гравий. Сколько килограммов каждого компонента нужно взять, чтобы получить 1200 кг бетона?

Представим смеси компонентов в виде системы уравнений. Обозначим цемент через - x, песок - y, гравий - z

\begin{cases} 
x + y + z = 1200 \\
x =  \frac{1}{4} \cdot (x + y + z) \\ 
y = \frac{1}{3} \cdot (x + y + z)  \\ 
\end{cases}

Преобразуем: \
3x - y - z = 0 \
-x + 2y - z = 0 \
 x + y + z = 1200 
 


In [404]:
import numpy as np
a = np.array([[3, -1, -1],[-1,2,-1],[1,1,1]])
b = np.array([0,0,1200])

#Решаем методом Крамера
det = np.linalg.det(a)
A_x = a.copy()
A_x[:, 0] = b 
det_x = np.linalg.det(A_x)
A_y = a.copy()
A_y[:, 1] = b
det_y = np.linalg.det(A_y)
A_z = a.copy()
A_z[:, 2] = b
det_z = np.linalg.det(A_z)
x = np.round(det_x / det)
y = np.round(det_y / det)
z = np.round(det_z / det)
print("Метод Крамера:")
print(f'x = {x}, y = {y} z = {z}')

#Решаем матричным методом
inv = np.linalg.inv(a) 
print(x1)
print("Матричный метод:")
print(f'x = {x1[0]}, y = {x1[1]} z = {x1[2]}')

#Решаем с помощью np.linalg.solve
x3 = np.round(np.linalg.solve(a, b))
print("Решение с помощью np.linalg.solve")
print(f'x = {x3[0]}, y = {x3[1]} z = {x3[2]}')


Метод Крамера:
x = 300.0, y = 400.0 z = 500.0
[300. 400. 500.]
Матричный метод:
x = 300.0, y = 400.0 z = 500.0
Решение с помощью np.linalg.solve
x = 300.0, y = 400.0 z = 500.0
